### ISSUE TITLE
HackRF One TypeError Unexpected Type

### ISSUE THREAD

**Issue by ThreeCalories** [xmikos/qspectrumanalyzer#101]
When I attempt to run hackrf_sweep I get a TypeError unexpected 'float' type.
```
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/home/threecalories/.local/lib/python3.10/site-packages/qspectrumanalyzer/__main__.py", line 368, in on_startButton_clicked
    self.start()
  File "/home/threecalories/.local/lib/python3.10/site-packages/qspectrumanalyzer/__main__.py", line 303, in start
    self.progressbar.setRange(0, self.intervalSpinBox.value() * 1000)
TypeError: setRange(self, int, int): argument 2 has unexpected type 'float'
```
Any help resolving this would be much appreciated.

**Comment by courtarro** [comment]
Not the developer, but this looks related to [issues in how Python 3.10 handles float and int types](https://bugs.launchpad.net/rapid/+bug/1946407). The literal `1000` is obviously an int, but even though `self.intervalSpinBox.value()` should always be an int, maybe Python is returning a float for that? Otherwise I guess the workaround is to wrap `int`:

`int(self.intervalSpinBox.value() * 1000)`

Or if you have Python 3.9 give that a shot. [See also](https://github.com/heartexlabs/labelImg/issues/811).
