### ISSUE TITLE
typeError : setRange issue

### ISSUE THREAD

**Issue by sonirohit3** [xmikos/qspectrumanalyzer#109]
I am using LimeSDR and it's being detected by soapy_power but getting following error when start is clicked:

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
libGL error: pci id for fd 22: 1ab8:0010, driver (null)
pci id for fd 23: 1ab8:0010, driver (null)
Traceback (most recent call last):
  File "/home/rohit/.local/lib/python3.10/site-packages/qspectrumanalyzer/__main__.py", line 368, in on_startButton_clicked
    self.start()
  File "/home/rohit/.local/lib/python3.10/site-packages/qspectrumanalyzer/__main__.py", line 303, in start
    self.progressbar.setRange(0, self.intervalSpinBox.value() * 1000)
TypeError: setRange(self, int, int): argument 2 has unexpected type 'float'

My question is what should be written in device field in settings?

Below are logs from ? icon
Detected SoapySDR devices:
  driver=lime, serial=0009081C05C32A35, label=LimeSDR-USB [USB 3.0] 9081C05C32A35

Selected device: LimeSDR-USB
  Available RX channels:
    0, 1
  Available antennas:
    NONE, LNAH, LNAL, LNAW, LB1, LB2
  Available tunable elements:
    RF, BB
  Available amplification elements:
    TIA, LNA, PGA
  Available device settings:
    SAVE_CONFIG ...  - Save LMS settings to file (default: )
    LOAD_CONFIG ...  - Load LMS settings from file (default: )
    OVERSAMPLING ...  - oversampling ratio (0 - auto) (default: )
  Available stream arguments:
    bufferLength ... Buffer Length - The buffer transfer size over the link. (default: 0)
    latency ... Latency - Latency vs. performance (default: 0.5)
    linkFormat ... Link Format - The format of the samples over the link. (default: CS16)
    skipCal ... Skip Calibration - Skip automatic activation calibration. (default: false)
    alignPhase ... align phase - Attempt to align phase of Rx channels. (default: false)
  Allowed gain range [dB]:
    -12.00 - 61.00
  Allowed frequency range [MHz]:
    0.00 - 3800.00
  Allowed sample rates [MHz]:
    0.10 - 61.44
  Allowed bandwidths [MHz]:
    1.40 - 130.00

**Comment by mboros1** [comment]
Getting the same error, seems to be an issue with python 3.10?
