### ISSUE TITLE
Using RPi B+

### ISSUE THREAD

**Issue by cpbridges** [xmikos/qspectrumanalyzer#3]
I'm trying to get this going on an RPi B+. Have all the dependancies sorted and rtl_power_fftw, all working there (with no sudo). The program loads fine too. But I get the following error. Any thoughts or things you want me to try? Best, Chris

```
rtl_power_fftw params:
{'bin_size': 10.0,
 'bins': 256,
 'crop': 0.0,
 'freq_range': 21000000.0,
 'gain': 0,
 'hops': 9,
 'interval': 1.0,
 'min_overhang': 0.0,
 'overhang': 255000.0,
 'overlap': 0.0,
 'ppm': 0,
 'sample_rate': 2560000,
 'single_shot': True,
 'start_freq': 87.0,
 'stop_freq': 108.0,
 'time': 0.1111111111111111}

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/qspectrumanalyzer/__main__.py", line 336, in run
    self.process_start()
  File "/usr/local/lib/python3.2/dist-packages/qspectrumanalyzer/__main__.py", line 499, in process_start
    self.process = subprocess.Popen(cmdline, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
AttributeError: 'module' object has no attribute 'DEVNULL'
```

Confirmation of rtl_test, rtl_power_fftw:

```
pi@raspberrypi ~ $ rtl_test -t
Found 1 device(s):
  0:  Generic, RTL2832U, SN: 77771111153705700

Using device 0: Generic RTL2832U
Found Rafael Micro R820T tuner
Supported gain values (29): 0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6 
[R82XX] PLL not locked!
Sampling at 2048000 S/s.
No E4000 tuner found, aborting.
```

```
pi@raspberrypi ~ $ rtl_power_fftw 
Found Rafael Micro R820T tuner
Available gains (in 1/10th of dB): 0, 9, 14, 27, 37, 77, 87, 125, 144, 157, 166, 197, 207, 229, 254, 280, 297, 328, 338, 364, 372, 386, 402, 421, 434, 439, 445, 480, 496
Selected nearest available gain: 372 (37.2 dB)
Exact sample rate is: 2000000.052982 Hz
Actual sample rate: 2000000 Hz
Number of bins: 512
Total number of (complex) samples to collect: 819200
Buffer length: 1638400
Number of device readouts: 1
Number of averaged spectra: 1600
Estimated time of measurements: 0.4096 seconds
Device tuned to: 1420405752 Hz
Acquisition started at 2015-12-12 13:15:44 UTC
Acquisition done at 2015-12-12 13:15:44 UTC
Actual number of (complex) samples collected: 819200
Actual number of device readouts: 1
Number of successful readouts: 1
Actual number of averaged spectra: 1600
Effective integration time: 0.4096 seconds
# rtl-power-fftw output
# Acquisition start: 2015-12-12 13:15:44 UTC
# Acquisition end: 2015-12-12 13:15:44 UTC
#
# frequency [Hz] power spectral density [dB/Hz]
1.41940575e+09 -26.9757
1.41940966e+09 -21.61
1.41941356e+09 -23.8093
1.41941747e+09 -23.5797
1.41942138e+09 -23.2471
1.41942528e+09 -25.2368
1.41942919e+09 -22.4432
1.4194331e+09 -21.4697
blah blah blah
1.42138622e+09 -25.1305
1.42139013e+09 -20.9614
1.42139403e+09 -24.4444
1.42139794e+09 -22.0543
1.42140185e+09 -27.3043

Buffer queue histogram: 0 0 0 0 0 1
```

**Comment by xmikos** [comment]
You have too old version of Python, subprocess.DEVNULL has been added in Python 3.3.
