### ISSUE TITLE
Windows supported?

### ISSUE THREAD

**Issue by gvanem** [xmikos/qspectrumanalyzer#36]
The main-page (in README.rst) gave me the impression Windows is supported. But I'm not sure after these simple steps:
```
git clone https://github.com/xmikos/qspectrumanalyzer.git
cd qspectrumanalyzer
py -3 setup.py -h
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
  ...
  File "F:\ProgramFiler\Python36\Lib\site-packages\QSpectrumAnalyzer\subprocess.py", line 4, in <module>
    PIPE = subprocess.PIPE
AttributeError: module 'subprocess' has no attribute 'PIPE'
```
What?

**Comment by Hoernchen** [comment]
This is caused by the classic name shadowing trap - the file is called subprocess, and imports the subprocess package provided by python. Easy fix: rename the file (and the import statements in the backends files).
