### ISSUE TITLE
ImportError: cannot import name 'QtCore'

### ISSUE THREAD

**Issue by bogdanr** [xmikos/qspectrumanalyzer#38]
When I try to run this software I am getting this error:

```
nimblex:~# qspectrumanalyzer 
Traceback (most recent call last):
  File "/usr/bin/qspectrumanalyzer", line 11, in <module>
    load_entry_point('QSpectrumAnalyzer==2.1.0', 'gui_scripts', 'qspectrumanalyzer')()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python3.6/site-packages/qspectrumanalyzer/__main__.py", line 5, in <module>
    from Qt import QtCore, QtGui, QtWidgets, __binding__
ImportError: cannot import name 'QtCore'
```
What package am I missing?

I have QT5 and PyQT5.

It would be nice to have a check during install that makes sure this package is not missing.

**Comment by xmikos** [comment]
Hello, sorry that it took that long, I didn't have time to work on QSpectrumAnalyzer but it should be better now.

Now for your question - are you sure that you have Python 3 version of PyQt5 installed and not Python 2? What distribution are you using?
