### ISSUE TITLE
not working on fedora 28

### ISSUE THREAD

**Issue by TLeconte** [xmikos/qspectrumanalyzer#55]
I try to istall all dependecies, then install with : 

>  pip3 install --user .

without  problems, but when launching qspectrumanalyser , I got : 

> Traceback (most recent call last):
>   File "/home/leconte/.local/bin/qspectrumanalyzer", line 11, in <module>
>     load_entry_point('QSpectrumAnalyzer==2.2.0', 'gui_scripts', 'qspectrumanalyzer')()
>   File "/home/leconte/.local/lib/python3.6/site-packages/qspectrumanalyzer/__main__.py", line 646, in main
>     window = QSpectrumAnalyzerMainWindow()
>   File "/home/leconte/.local/lib/python3.6/site-packages/qspectrumanalyzer/__main__.py", line 261, in __init__
>     self.setup_power_thread()
>   File "/home/leconte/.local/lib/python3.6/site-packages/qspectrumanalyzer/__main__.py", line 272, in setup_power_thread
>     self.data_storage = DataStorage(max_history_size=settings.value("waterfall_history_size", 100, int))
> TypeError: PySide.QtCore.QSettings.value(): too many arguments

any ideas ?

**Comment by cyberxml** [comment]
pip install PyQt5

worked for me as last step on Fedora 30
