### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by catalinalb** [xmikos/qspectrumanalyzer#76]
Hello,

I am running ubuntu 18.04 LTS with gnuradio installed using pybombs I did manage to have gr-fosphor running inside the gnuradio. 

I did installed qspectrumanalyzer with command: sudo python setup.py install
Didn't get any errors at the installation output but when I try to run it gives the following output:

Traceback (most recent call last):
  File "/usr/local/bin/qspectrumanalyzer", line 11, in <module>
    load_entry_point('QSpectrumAnalyzer==2.2.0', 'gui_scripts', 'qspectrumanalyzer')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/QSpectrumAnalyzer-2.2.0-py2.7.egg/qspectrumanalyzer/__main__.py", line 7, in <module>
    from qspectrumanalyzer import backends
  File "/usr/local/lib/python2.7/dist-packages/QSpectrumAnalyzer-2.2.0-py2.7.egg/qspectrumanalyzer/backends/__init__.py", line 5, in <module>
    from qspectrumanalyzer import subprocess
  File "/usr/local/lib/python2.7/dist-packages/QSpectrumAnalyzer-2.2.0-py2.7.egg/qspectrumanalyzer/subprocess.py", line 57
    def __init__(self, *pargs, console=True, **kwargs):
                                     ^
SyntaxError: invalid syntax

**Comment by catalinalb** [comment]
my mistake! so it seems that after running python setup.py install I have got some errors. Here they are:

gnuradio@xps:~/qspectrumanalyzer$ sudo python setup.py install
[sudo] password for gnuradio: 
running install
running bdist_egg
running egg_info
writing requirements to QSpectrumAnalyzer.egg-info/requires.txt
writing QSpectrumAnalyzer.egg-info/PKG-INFO
writing top-level names to QSpectrumAnalyzer.egg-info/top_level.txt
writing dependency_links to QSpectrumAnalyzer.egg-info/dependency_links.txt
writing entry points to QSpectrumAnalyzer.egg-info/entry_points.txt
reading manifest file 'QSpectrumAnalyzer.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'QSpectrumAnalyzer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/qspectrumanalyzer_persistence.ui -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/persistence.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/qspectrumanalyzer.ui -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/ui_qspectrumanalyzer_baseline.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/ui_qspectrumanalyzer_persistence.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/qspectrumanalyzer_baseline.ui -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/ui_qspectrumanalyzer_settings_help.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/ui_qspectrumanalyzer_smoothing.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
creating build/bdist.linux-x86_64/egg/qspectrumanalyzer/languages
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/languages/qspectrumanalyzer_cs.ts -> build/bdist.linux-x86_64/egg/qspectrumanalyzer/languages
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/languages/qspectrumanalyzer_cs.qm -> build/bdist.linux-x86_64/egg/qspectrumanalyzer/languages
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/__init__.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/subprocess.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/colors.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/qspectrumanalyzer_settings_help.ui -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/version.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/qspectrumanalyzer.svg -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/settings.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/qspectrumanalyzer_smoothing.ui -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/smoothing.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/ui_qspectrumanalyzer_colors.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/data.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/__main__.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
creating build/bdist.linux-x86_64/egg/qspectrumanalyzer/backends
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/backends/rx_power.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer/backends
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/backends/__init__.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer/backends
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/backends/soapy_power.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer/backends
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/backends/rtl_power.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer/backends
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/backends/hackrf_sweep.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer/backends
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/backends/rtl_power_fftw.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer/backends
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/windows.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/baseline.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/plot.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/qspectrumanalyzer_colors.ui -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/qspectrumanalyzer_settings.ui -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/ui_qspectrumanalyzer.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/utils.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
copying build/lib.linux-x86_64-2.7/qspectrumanalyzer/ui_qspectrumanalyzer_settings.py -> build/bdist.linux-x86_64/egg/qspectrumanalyzer
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/persistence.py to persistence.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/ui_qspectrumanalyzer_baseline.py to ui_qspectrumanalyzer_baseline.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/ui_qspectrumanalyzer_persistence.py to ui_qspectrumanalyzer_persistence.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/ui_qspectrumanalyzer_settings_help.py to ui_qspectrumanalyzer_settings_help.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/ui_qspectrumanalyzer_smoothing.py to ui_qspectrumanalyzer_smoothing.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/subprocess.py to subprocess.pyc
  File "build/bdist.linux-x86_64/egg/qspectrumanalyzer/subprocess.py", line 57
    def __init__(self, *pargs, console=True, **kwargs):
                                     ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/colors.py to colors.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/version.py to version.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/settings.py to settings.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/smoothing.py to smoothing.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/ui_qspectrumanalyzer_colors.py to ui_qspectrumanalyzer_colors.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/data.py to data.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/__main__.py to __main__.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/backends/rx_power.py to rx_power.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/backends/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/backends/soapy_power.py to soapy_power.pyc
  File "build/bdist.linux-x86_64/egg/qspectrumanalyzer/backends/soapy_power.py", line 204
    print(e, file=sys.stderr)
                 ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/backends/rtl_power.py to rtl_power.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/backends/hackrf_sweep.py to hackrf_sweep.pyc
  File "build/bdist.linux-x86_64/egg/qspectrumanalyzer/backends/hackrf_sweep.py", line 151
    print(e, file=sys.stderr)
                 ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/backends/rtl_power_fftw.py to rtl_power_fftw.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/windows.py to windows.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/baseline.py to baseline.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/plot.py to plot.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/ui_qspectrumanalyzer.py to ui_qspectrumanalyzer.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/qspectrumanalyzer/ui_qspectrumanalyzer_settings.py to ui_qspectrumanalyzer_settings.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/share
creating build/bdist.linux-x86_64/egg/share/applications
copying qspectrumanalyzer.desktop -> build/bdist.linux-x86_64/egg/share/applications
creating build/bdist.linux-x86_64/egg/share/pixmaps
copying qspectrumanalyzer.png -> build/bdist.linux-x86_64/egg/share/pixmaps
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying QSpectrumAnalyzer.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying QSpectrumAnalyzer.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying QSpectrumAnalyzer.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying QSpectrumAnalyzer.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying QSpectrumAnalyzer.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying QSpectrumAnalyzer.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
qspectrumanalyzer.__main__: module references __file__
creating 'dist/QSpectrumAnalyzer-2.2.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing QSpectrumAnalyzer-2.2.0-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/QSpectrumAnalyzer-2.2.0-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/QSpectrumAnalyzer-2.2.0-py2.7.egg
Extracting QSpectrumAnalyzer-2.2.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
  File "/usr/local/lib/python2.7/dist-packages/QSpectrumAnalyzer-2.2.0-py2.7.egg/qspectrumanalyzer/subprocess.py", line 57
    def __init__(self, *pargs, console=True, **kwargs):
                                     ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/QSpectrumAnalyzer-2.2.0-py2.7.egg/qspectrumanalyzer/backends/hackrf_sweep.py", line 151
    print(e, file=sys.stderr)
                 ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python2.7/dist-packages/QSpectrumAnalyzer-2.2.0-py2.7.egg/qspectrumanalyzer/backends/soapy_power.py", line 204
    print(e, file=sys.stderr)
                 ^
SyntaxError: invalid syntax

QSpectrumAnalyzer 2.2.0 is already the active version in easy-install.pth
Installing qspectrumanalyzer script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/QSpectrumAnalyzer-2.2.0-py2.7.egg
Processing dependencies for QSpectrumAnalyzer==2.2.0
Searching for Qt.py==1.2.1
Best match: Qt.py 1.2.1
Processing Qt.py-1.2.1-py2.7.egg
Qt.py 1.2.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/Qt.py-1.2.1-py2.7.egg
Searching for pyqtgraph==0.10.0
Best match: pyqtgraph 0.10.0
Adding pyqtgraph 0.10.0 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for soapy-power==1.6.1
Best match: soapy-power 1.6.1
Processing soapy_power-1.6.1-py2.7.egg
soapy-power 1.6.1 is already the active version in easy-install.pth
Installing soapy_power script to /usr/local/bin

Using /usr/local/lib/python2.7/dist-packages/soapy_power-1.6.1-py2.7.egg
Searching for SimpleSpectral==1.0.0
Best match: SimpleSpectral 1.0.0
Processing SimpleSpectral-1.0.0-py2.7.egg
SimpleSpectral 1.0.0 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/SimpleSpectral-1.0.0-py2.7.egg
Searching for SimpleSoapy==1.5.1
Best match: SimpleSoapy 1.5.1
Processing SimpleSoapy-1.5.1-py2.7.egg
SimpleSoapy 1.5.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/SimpleSoapy-1.5.1-py2.7.egg
Searching for numpy==1.13.3
Best match: numpy 1.13.3
Adding numpy 1.13.3 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for QSpectrumAnalyzer==2.2.0
gnuradio@xps:~/qspectrumanalyzer$
